# Generated by Django 6.0.5 on 2026-05-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_title_product_is_promotional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/slider/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotional', to='products.product')),
            ],
        ),
    ]
