# Generated by Django 6.0.5 on 2026-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_promotional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotional',
        ),
    ]
