# Generated by Django 6.0.5 on 2026-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brands', to='products.category'),
        ),
    ]
